TickTackToe/Controllers/AdminController.cs
using Core;
using Core.DB;
using Core.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TickTackToe.Models;

namespace TickTackToe.Controllers
{
    public class AdminController : BaseController
    {
        public IGameService GameService { get; set; }

        public AdminController()
        { }
        //
        // Get: /Admin/MainPage
        public ActionResult MainPage()
        {
            return View();
        }

        // Get: /Admin/GamersList
        public ActionResult GamersList()
        {
            var gamers = GameService.GetGamersList();
            var gamersVM = new GamersViewModel();
            gamersVM.Gamers = new List<Gamer>();

            foreach (var gamer in gamers)
            {
                AddGamerToList(gamersVM.Gamers, gamer);
            }

            return View("GamersList", gamersVM);
        }
        private void AddGamerToList(List<Gamer> gamers, AspNetUser gamer)
        {
            gamers.Add(new Gamer()
            {
                Name = gamer.Name,
                Age = DateTime.UtcNow.ToLocalTime().Year - gamer.YearOrBirthday,
                UserName = gamer.UserName,
            });
        }
    }
}

TickTackToe/Controllers/BaseController.cs
using NLog;
using System;
using System.Resources;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace TickTackToe.Controllers
{
    public class BaseController : Controller
    {
        private readonly Logger _logger = LogManager.GetCurrentClassLogger();

        protected override IAsyncResult BeginExecuteCore(AsyncCallback callback, object state)
        {
            //  string cultureName = RouteData.Values["culture"] as string;
            string cultureName = null;
            // Attempt to read the culture cookie from Request
            HttpCookie cultureCookie = Request.Cookies["_culture"];
            if (cultureCookie != null)
                cultureName = cultureCookie.Value;
            else
                cultureName = Request.UserLanguages != null && Request.UserLanguages.Length > 0 ?
                        Request.UserLanguages[0] :  // obtain it from HTTP header AcceptLanguages
                        null;
            // Validate culture name
            cultureName = CultureHelper.GetImplementedCulture(cultureName); // This is safe

            // Modify current thread's cultures            
            Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo(cultureName);
            Thread.CurrentThread.CurrentUICulture = Thread.CurrentThread.CurrentCulture;

            return base.BeginExecuteCore(callback, state);
        }

        [AllowAnonymous]
        public ActionResult SetCulture(string culture)
        {
            // Validate input
            culture = CultureHelper.GetImplementedCulture(culture);
            // Save culture in a cookie
            //RouteData.Values["culture"] = culture;  // set culture
            HttpCookie cookie = Request.Cookies["_culture"];
            if (cookie != null)
                cookie.Value = culture;   // update cookie value
            else
            {
                cookie = new HttpCookie("_culture");
                cookie.Value = culture;
                cookie.Expires = DateTime.Now.AddYears(1);
            }
            Response.Cookies.Add(cookie);

            return Redirect(Request.UrlReferrer.AbsolutePath);
        }


        public ActionResult CurrentCulture()
        {
            return Json(Thread.CurrentThread.CurrentUICulture.ToString(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetResource(string id)
        {
            ResourceManager rm = new ResourceManager(typeof(Core.Resources.Resources));
            var translate = rm.GetString(id, Thread.CurrentThread.CurrentUICulture);
            return Json(translate, JsonRequestBehavior.AllowGet);
        }

    }
}

TickTackToe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@Core.Resources.Resources.TitleMainGame</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/cstmcss")
    @Scripts.Render("~/bundles/modernizr")
</head>
@{
    var culture = System.Threading.Thread.CurrentThread.CurrentUICulture.Name.ToLowerInvariant();
}
@helper selected(string c, string culture)
{
    if (c == culture)
    {
        @:checked="checked"
        }
}
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                </button>
                <img src="~/Content/imgs/logo.png" class="main-logo" />
                @Html.ActionLink(Core.Resources.Resources.TitleMainGame, "Index", "Home", new { area = "" }, new { @class = "navbar-brand logo" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink(Core.Resources.Resources.MainPage, "Index", "Home")</li>
                    <li>@Html.ActionLink(Core.Resources.Resources.AdminPage, "MainPage", "Admin")</li>
                </ul>
                <div class="main-localization">
                    @using (Html.BeginForm("SetCulture", "Base"))
                    {
                        <b>@Core.Resources.Resources.ChooseYourLanguage</b>
                        <span>
                            <input name="culture" id="en" value="en-us" type="radio" @selected("en-us", culture) />  @Core.Resources.Resources.English
                        </span>
                        <span>
                            <input name="culture" id="ru" value="ru" type="radio" @selected("ru", culture) /> @Core.Resources.Resources.Rus
                        </span>
                    }
                </div>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/cstm/localistart.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>